# FROM (base_image:tag)
# tensorflow images are based on ubuntu16.04 image
FROM pytorch-cuda102-cudnn7:latest

# RUN apt-get update && apt-get -y upgrade
# RUN apt-get -y install build-essential git
# RUN rm -rf /var/lib/apt/lists/*

# Add whatever you need here
RUN pip3 --no-cache-dir install --upgrade pip
# RUN pip3 --no-cache-dir install --upgrade git+https://github.com/tensorpack/dataflow.git
RUN pip3 --no-cache-dir install --upgrade python-prctl pathlib
# COPY entrypoint.sh /usr/local/bin/entrypoint.sh
# RUN chmod +x /usr/local/bin/entrypoint.sh
# RUN apt-get -y purge git
